version: '3'
services:
  web:
    build: ./
    volumes:
      - ./app:/app
    ports:
      - "8001:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: /bin/bash -c "service redis-server restart && flask run --host=0.0.0.0 --port=80"